---
title: Problem set 3 
date: 2026-09-25
---

# Overview

If you use AI to help solve any problem (and some of the 
problems request that you do so), please
provide information on 1) the model in use, 2) the prompt used to get help,
3) some comments on what you learned from the encounter.

Solutions to this problem set should be submitted as quarto documents.
Place the required file in your bst260 repository in folder "solutions" as "pset03.qmd"
Use the title "BST 260 Problem set 3: Logic, reading, guns and geography",
and put your
name as author in the yaml header.  Ensure that the HTML
to which your quarto document compiles has a good appearance.

# Propositional logic exercises

Notation: $\neg$ (not), $\wedge$ (and), $\lor$ (or), $\rightarrow$ (if...then), $\leftrightarrow$ (if and only if)

In your document you can use \LaTeX annotation for these connectives:

- `$\neg$` for negation
- `$\wedge$` for 'and'
- `$\lor$` for 'or'
- `$\rightarrow$` for 'if...then'
- `$\leftrightarrow$` for 'if and only if'


Illustration.  We consider the sentence

If Ana studies, then if she rests well, she will pass the exam.

We can use propositional variables

- S = Ana studies 
- R = Ana rests well 
- P = Ana passes the exam

We will formalize the sentence as $S \rightarrow (R \rightarrow P)$, and
suppose that the sentence is TRUE.  If Ana rested well and failed the
exam, what can we say about whether she studied?  Give all your reasoning.

A formal approach could be based on writing out the truth table.

| S | R | P | **S → (R → P)** |
|:---:|:---:|:---:|:---:|
| T | T | T | T |
| T | T | F | F |
| T | F | T | T |
| T | F | F | T |
| F | T | T | T |
| F | T | F | T |
| F | F | T | T |
| F | F | F | T |

We asserted that the sentence is true but P is false and R is true.
We can find this configuration only once in the truth table, on
the sixth line.  There S is F, so we conclude that Ana did not study.

Note that when I submitted the problem to the Luna chatbot in the
Harvard sandbox, it found

"This is an application of **modus tollens** to the outer implication: if $S$ were true, then $R \rightarrow P$ would have to be true, but it is false. Therefore $S$ must be false."

That's interesting.  I should be motivated to learn what **modus tollens** is,
might connect it to **modus ponens**, and might learn a short cut relative
to working out the truth table.

**Exercise 1**.  Formalize

If the coupon is valid, then the price is reduced or the shipping is free.

What conditions on coupon validity, price and shipping make the sentence false?
You do not need to write out the truth table but you may want to do so
to find the answer.  Do state your variables and write out the
formalization of the sentence.

Do this without a chatbot first.  Then confirm your answer with the chatbot.
If you find a discrepancy please add it into your problem set solutions.

**Exercise 2**.  Formalize

If it is not sunny and not warm then the picnic is cancelled.

What kinds of weather and picnic scheduling make the sentence false?

Same relationship to chatbot.  Formalize, try to find the values of
variables that make the sentence false, then confirm with chatbot.

**Exercise 3**.  Formalize

You may enter the contest if and only if you are a member or you have paid the fee.

Suppose you enter and the sentence is false.  What do we know about your
membership and fee payments?

# Reading and running code exercises

**Exercise 4**.  Install the `dslabs` package from CRAN.  After
```
library(dslabs)
```
use `?murders` to get help on the murders dataset that was used last year.
What is problematic about this dataset?

**Exercise 5**.  Use the commands

```
cdcmurd <- read.csv("https://tinyurl.com/cdcmurder")
dim(cdcmurd)
```

This acquires a dataset from the CDC that describes murder rates
over time in the 50 states and D.C.

The dataset is available at [https://www.cdc.gov/nchs/state-stats/deaths/homicide.html](https://www.cdc.gov/nchs/state-stats/deaths/homicide.html).  Note the definition of
the adjusted rate.  Does it make sense?

How many rows are available?

**Exercise 6**.  Why would one use the command
```
table(table(head(cdcmurd$Location,120)))
```
Compare the result of
```
table(table(head(cdcmurd$Location,153)))
```
and
```
head(table(cdcmurd$Location))
```
What do you learn about the `cdcmurd` data.frame on the basis of these
commands?  Hint: `table(cdcmurd$Location)` is quite unpleasant to look at.

You can use AI to get some reasoning about the value of the `table(table(`
construction.  Report what you learn here.

**Exercise 7**.  Before running the code, explain what
```
apply(cdcmurd,2,function(x) any(is.na(x)))
``` 
is doing.  Use `?apply` if necessary.  

**Exercise 8**.  What is 
```
cdcmurd[which(is.na(cdcmurd$Death.Rate)),] |> nrow()
```
doing?  Run it.

**Exercise 9.  Elegance of dplyr.**

Be sure the dplyr package is installed.  Try

```
library(dplyr)
cdcmurd |> filter(is.na(Death.Rate)) |> count()
```
What is the difference between the outcome here and that of Exercise 8?

Here's a two-line command, which you can run if the commands
above have all suceeded.
```
cdcmurd |> filter(is.na(Death.Rate)) |> 
    group_by(Location) |> summarise(mn=mean(Deaths))
```
Now look at `median(cdcmurd$Deaths)`.  Form a conjecture on
why the death rates are missing when they are?  Use AI to check your
conjecture and report what you learned.

**Exercise 10.  Visualization.**

Ensure that ggplot2, ggbeeswarm, and plotly are installed in your version of R.
Read this code before you run it.
```
myp <- cdcmurd |> filter(YEAR %in% c(2019,2020,2021,2022)) |> 
  ggplot(aes(factor(YEAR), Death.Rate, text=Location)) + 
  geom_beeswarm() + geom_boxplot() 
ggplotly(myp)
```
Answer the following questions:

- Line 1 will filter the cdcmurd data frame to how many rows?
- Line 2 creates *aesthetic mappings* from the filtered cdcmurd dataset.
Owing to the default parameterization of `aes`, which variable will be
used to define the y coordinates of the plot?
- Line 3 sets up two statistical views of the data.  What aspects of
the data are presented in the boxplot?  What aspects are presented
using beeswarm?  Try to answer the question using the R documentation,
then compare your answer to that provided by a chatbot.  Provide
both outputs.

Run the code and hover over the points.  Note that for the points
outside the boxplot, you need to put your mouse pointer right over the
data point to get a report on the location and rate corresponding
to the point.  Take a screenshot of your display and hand it to the
GPT-Luna in the harvard AI sandbox.  Ask it for methods of improving
the display.  Can you implement some?

**Exercise 11: Gun safety legislation.**

Ensure that the readxl package is installed.  Use
```
download.file("https://tinyurl.com/randgunlaw", (tf <- tempfile()))
lawdat = read_xlsx(tf, 2)
```
This will obtain a table assembled by the RAND Corporation summarizing
aspects of gun control legislation in the US.  The source URL was
[https://www.rand.org/pubs/tools/TLA243-2-v4.html](https://www.rand.org/pubs/tools/TLA243-2-v4.html).

Exercise 11.a. The download command is complex.  How can you make it
more interpretable?

Exercise 11.b. What is the purpose of the second argument to the `read_xlsx`
command?

Exercise 11.c. How many rows are returned?

**Dynamic tabulation.**

Ensure that the DT package has been installed.  Use
```
datatable(lawdat[,c(1,3,6,8,9,10,12)])
```
and note that you can set the number of lines displayed.
You can also sort the rows of the table by clicking on
the column names.

Exercise 11.d. Sort the table by "Effective Date Year".  What is the
year of the earliest recorded gun legislation?

Exercise 11.e. Provide dplyr code that retrieves the year of the earliest recorded
gun legislation.  You can use AI to find the code.  Tell what your
prompt was, show the code and the result.

Exercise 11.f. Here's another multiline command:

```
lawdat |> select(`Type of Change`, `Effect`) |> 
   group_by(`Type of Change`, `Effect`) |> 
   summarise(n=n()) |> arrange(desc(n))
```

When given to R with dplyr version 1.2.1, we get:
```
`summarise()` has regrouped the output.
ℹ Summaries were computed grouped by Type of Change and Effect.
ℹ Output is grouped by Type of Change.
ℹ Use `summarise(.groups = "drop_last")` to silence this message.
ℹ Use `summarise(.by = c(Type of Change, Effect))` for per-operation grouping
  (`?dplyr::dplyr_by`) instead.
# A tibble: 7 × 3
# Groups:   Type of Change [4]
  `Type of Change` Effect          n
  <chr>            <chr>       <int>
1 Implement        Restrictive  1241
2 Modify           Restrictive   215
3 Modify           Permissive    192
4 Implement        Permissive    187
5 Repeal           Permissive     59
6 Repeal           Restrictive     6
7 See note         Permissive      2
```

Exercise 11.f.1: What do you regard as the "take home message" of the table above?

Exercise 11.f.2: Plop the command given above (that generates the table) into
the AI sandbox using GPT 5.6 Luna.  You will probably get some advice on
how the command can be simplified.  Show the simplified approach and its result.

Exercise 12.  With dplyr and ggplot2 attached, use
```
lawdat |> filter(Effect=="Permissive") |> 
   summarize(n=n(), .by=`Effective Date Year`) |>  
   ggplot(aes(x=`Effective Date Year`, y=n)) + geom_point()
```
Explain the code and the plot.  Would it be possible to associate
each point with a US state?  Why or why not?

Exercise 13.  Which state (or states, there may be ties) have the largest
frequencies of legislative changes that have "Permissive" effects?
Which state (or states) have the largest frequencies of legislative
changes that have "Restrictive" effects?

Exercise 14.  Careful linkage between the RAND and CDC datasets will
be explored in future problem sets.  Explain the choice of
states used in the plot below, and discuss the interpretation
of any patterns you see.  With your interpretive remarks, include
commentary on how to make the interpretation more precise with
additional work on data filtering and combination.
```
cdcmurd |> filter(Location %in% c("CA", "NY", "MS", "TN")) |> 
   ggplot(aes(x=YEAR, y=Death.Rate, colour=Location)) + geom_point() 
```

Extra credit exercise.  The file `https://raw.githubusercontent.com/vjcitn/2026vjc/main/fakeratemap.R` includes agentically generated code to produce a map with fabricated
murder rate statistics.  Use download.file to get a copy on your local machine
and modify it to use a set of rates from the `cdcmurd` data.frame.
Embed the interactive map in your quarto document.
